Add GraphQL loader
CodingZeal/create-react-app pull request #14
Opened 2017-07-14 18:42 UTC by lexun

Loads GraphQL queries from .graphql files

- Does not process GraphQL ASTs on client-side
- Enables queries to be separated from logic

http://dev.apollodata.com/react/webpack.html

2017-07-14 18:52 UTC, randycoulman reviewed
What's here looks good, but do we also need jest-transform-graphql for our tests as mentioned here: http://dev.apollodata.com/react/webpack.html#Jest

2017-07-14 21:22 UTC, bmatto approved these changes
🎉

2017-07-17 15:43 UTC, randycoulman requested changes

2017-07-17 15:43 UTC, randycoulman commented on packages/react-scripts/scripts/utils/createJestConfig.js
> +      '^.+\\.(gql|graphql)$': require.resolve('jest-transform-graphql'),
I think this should be `resolve` instead of `require.resolve`; `resolve` is an injected dependency, it appears.

2017-07-17 16:00 UTC, lexun commented on packages/react-scripts/scripts/utils/createJestConfig.js
> +      '^.+\\.(gql|graphql)$': require.resolve('jest-transform-graphql'),
I started with `resolve`, but it doesn't work here. They're using it to load local config files that may be in a different place after you eject. In each of those files they're using `require.resolve` for this sort of thing.

2017-07-17 16:26 UTC, randycoulman approved these changes

2017-07-17 16:49 UTC, merged